url: "https://changelog.optimism.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/"
title: "Optimism Changelog"
author: The Optimism Team
description: Optimism's public changelog.
collections:
  post-mortems:
    output: true
exclude:
  - README.md
plugins:
  - jekyll-feed